security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html

            # FROM https://symfony.com/doc/current/reference/configuration/security.html
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: false
                default_target_path: LuckyRoute
                #target_path_parameter:          _target_path
                use_referer:                    false

            provider: our_db_provider

            logout:
                path: /logout
                target: /

# only needed if you have roles per users
#    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/lucky, roles: ROLE_ADMIN }
