version: "3"
services:
  my_dbec_web_server:
    build: .
    image: joseph1248/dbec
    ports:
      - "80:80"

  my_dbec_jenkins_server:
    image: getintodevops/jenkins-withdocker:lts
    restart: always
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./../vol_jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock