version: "3"
services:
  dbec_app:
    build: .
    ports:
        - "80:80"
    depends_on:
        - dbec_db

  dbec_db:
    image: mariadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - "MYSQL_ROOT_PASSWORD=dbpassword"
      - "MYSQL_USER=dbuser"
      - "MYSQL_PASSWORD=dbpassword"
      - "MYSQL_DATABASE=db_cloner_dev"
    ports:
      - "3306:3306"
