version: "3"
services:
  my_dbec_database_server:
    image: mariadb
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=ilkj531665s1dcs6df31asd16"
      - "MYSQL_USER=dbuser"
      - "MYSQL_PASSWORD=dbpassword"
      - "MYSQL_DATABASE=db_cloner_dev"
    ports:
      - "3306:3306"
    volumes:
      - ./docker-entrypoint-initdb.d/a_schema.sql:/docker-entrypoint-initdb.d/a_schema.sql
      - ./docker-entrypoint-initdb.d/b_fixture.sql:/docker-entrypoint-initdb.d/b_fixture.sql

  my_dbec_web_server:
    build: .
    image: joseph1248/dbec
    ports:
      - "80:80"
    links:
      - my_dbec_database_server

  my_dbec_jenkins_server:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./vol_jenkins_home:/var/jenkins_home

  my_dbec_adminer_server:
    image: adminer
    restart: always
    ports:
      - 8081:8081

