# config/routes.yaml


# -----------  CONNECTIONS ROUTES ----------------------------


ConnectionsListRoute:
    methods: [GET]
    path: /connections
    controller: App\Controller\ConnectionController::getAll

ConnectionAddRoute:
    methods: [POST]
    path: /connection/new
    controller: App\Controller\ConnectionController::post

ConnectionEditRoute:
    methods: [PATCH]
    path: /connection/edit
    controller: App\Controller\ConnectionController::patch

ConnectionGetRoute:
    methods: [GET]
    path: /connection/{id}
    controller: App\Controller\ConnectionController::getOne

ConnectionDeleteRoute:
    methods: [DELETE]
    path: /connection/{id}
    controller: App\Controller\ConnectionController::delete


# -----------  GENERIC ROUTES ----------------------------


configRoute:
    methods: [GET]
    path: /config
    controller: App\Controller\ConfigController::getConfig

dashboardRoute:
    methods: [GET]
    path: /dashboard
    controller: App\Controller\DashboardController::dashboard

login:
    methods: [GET,POST]
    path: /login
    controller: App\Controller\SecurityController::login

register:
    methods: [GET,POST]
    path: /register
    controller: App\Controller\SecurityController::register

exceptionRoute:
    methods: [GET]
    path: /log_exception
    controller: App\Controller\SecurityController::getOneException

indexRoute:
    methods: [GET]
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /login
        permanent: true

logoutRoute:
    methods: [GET]
    path: /logout
