# config/routes.yaml


# -----------  CONNECTIONS ROUTES ----------------------------


ConnectionsList:
    methods: [GET]
    path: /connections
    controller: App\Controller\ConnectionController::getAll

ConnectionAdd:
    methods: [POST]
    path: /connection/new
    controller: App\Controller\ConnectionController::post

ConnectionEdit:
    methods: [PATCH]
    path: /connection/edit
    controller: App\Controller\ConnectionController::patch

ConnectionGet:
    methods: [GET]
    path: /connection/{id}
    controller: App\Controller\ConnectionController::getOne

ConnectionDelete:
    methods: [DELETE]
    path: /connection/{id}
    controller: App\Controller\ConnectionController::delete


# -----------  GENERIC ROUTES ----------------------------


configRoute:
    methods: [GET]
    path: /config
    controller: App\Controller\ConfigController::getConfig

dashboardRoute:
    methods: [GET]
    path: /dashboard
    controller: App\Controller\DashboardController::dashboard

login:
    methods: [GET,POST]
    path: /login
    controller: App\Controller\SecurityController::login

index:
    methods: [GET]
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /login
        permanent: true

logout:
    methods: [GET]
    path: /logout
