# config/routes.yaml
 
indexRoute:
    path: /
    controller: App\Controller\IndexController::index

luckyRoute:
    path: /lucky
    controller: App\Controller\LuckyController::number

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
