# config/routes.yaml
 
luckyRoute:
    path: /lucky
    controller: App\Controller\LuckyController::number

login:
    path: /login
    controller: App\Controller\SecurityController::login

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /login
        permanent: true

logout:
    path: /logout
