# config/routes.yaml
 
LuckyRoute:
    path: /lucky
    controller: App\Controller\LuckyController::number

index:
    path: /
    controller: App\Controller\IndexController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
