# config/routes.yaml


# -----------  CONNECTIONS ROUTES ----------------------------


ConnectionsList:
    path: /connections
    controller: App\Controller\ConnectionController::getAll

ConnectionAdd:
    path: /connection/new
    controller: App\Controller\ConnectionController::getNew

ConnectionGet:
    path: /connection/{id}
    controller: App\Controller\ConnectionController::getOne

#ConnectionEdit:
#    path: /connection/{id}
#    controller: App\Controller\ConnectionController::patch


# -----------  GENERIC ROUTES ----------------------------


configRoute:
    path: /config
    controller: App\Controller\ConfigController::getConfig

dashboardRoute:
    path: /dashboard
    controller: App\Controller\DashboardController::dashboard

login:
    path: /login
    controller: App\Controller\SecurityController::login

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /login
        permanent: true

logout:
    path: /logout
