# config/routes.yaml
 
dashboardRoute:
    path: /dashboard
    controller: App\Controller\DashboardController::dashboard

login:
    path: /login
    controller: App\Controller\SecurityController::login

index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /login
        permanent: true

logout:
    path: /logout
